<?php

namespace AppBundle\Repository;

/**
 * FunkcjonalnosciRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FunkcjonalnosciRepository extends \Doctrine\ORM\EntityRepository
{
}
