<?php

namespace AppBundle\Repository;

/**
 * PoleceniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoleceniaRepository extends \Doctrine\ORM\EntityRepository
{
}
