<?php

namespace AppBundle\Repository;

/**
 * PoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoRepository extends \Doctrine\ORM\EntityRepository
{
}
